[package]
name = "meicho_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "meicho_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
